//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyFM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class STR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal STR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyFM.STR", typeof(STR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sky.fm player © Konstantin, 2012-2013.
        /// </summary>
        public static string about_copyright {
            get {
                return ResourceManager.GetString("about_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p align=&quot;Left&quot;&gt;Chinese localization: &lt;a href=&quot;http://www.facebook.com/gordon.chou.18&quot;&gt;Gordon Chou&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string about_localization_richtext {
            get {
                return ResourceManager.GetString("about_localization_richtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Includes source code from &lt;a href=&quot;http://kawagoe.codeplex.com/&quot;&gt;Kawagoe Toolkit&lt;/a&gt;, © Andréas Saudemont.&lt;/p&gt;.
        /// </summary>
        public static string about_thirdparty_richtext {
            get {
                return ResourceManager.GetString("about_thirdparty_richtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about this app.
        /// </summary>
        public static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p align=&quot;Left&quot;&gt;&lt;a href=&quot;http://www.sky.fm/&quot;&gt;Sky.fm&lt;/a&gt; is a registered trademark.&lt;/p&gt;
        ///&lt;p&gt;The author of this mobile application is a sky.fm premium subscriber, aside of that he has no relations to sky.fm. He believes such usage of the trade mark is fair use, and is thus protected by the First Amendment to the United States Constitution, and other laws.&lt;/p&gt;.
        /// </summary>
        public static string about_trademark_richtext {
            get {
                return ResourceManager.GetString("about_trademark_richtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0}, {1}.
        /// </summary>
        public static string about_version_fmt {
            get {
                return ResourceManager.GetString("about_version_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about this application.
        /// </summary>
        public static string appbar_about {
            get {
                return ResourceManager.GetString("appbar_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login to sky.fm premium.
        /// </summary>
        public static string appbar_login {
            get {
                return ResourceManager.GetString("appbar_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout from sky.fm premium.
        /// </summary>
        public static string appbar_logout {
            get {
                return ResourceManager.GetString("appbar_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing preferences.
        /// </summary>
        public static string appbar_preferences {
            get {
                return ResourceManager.GetString("appbar_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channel list in the server response..
        /// </summary>
        public static string error_json_no_channels_list {
            get {
                return ResourceManager.GetString("error_json_no_channels_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected JSON.
        /// </summary>
        public static string error_json_parse {
            get {
                return ResourceManager.GetString("error_json_parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string login_btn_login {
            get {
                return ResourceManager.GetString("login_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip login.
        /// </summary>
        public static string login_btn_skiplogin {
            get {
                return ResourceManager.GetString("login_btn_skiplogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        public static string login_error_password {
            get {
                return ResourceManager.GetString("login_error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter login.
        /// </summary>
        public static string login_error_user {
            get {
                return ResourceManager.GetString("login_error_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email:.
        /// </summary>
        public static string login_lbl_mail {
            get {
                return ResourceManager.GetString("login_lbl_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password:.
        /// </summary>
        public static string login_lbl_password {
            get {
                return ResourceManager.GetString("login_lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to sky.fm premium:.
        /// </summary>
        public static string login_login {
            get {
                return ResourceManager.GetString("login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading, please wait….
        /// </summary>
        public static string login_pending {
            get {
                return ResourceManager.GetString("login_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or, press this button for free streams:.
        /// </summary>
        public static string login_skiplogin {
            get {
                return ResourceManager.GetString("login_skiplogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to sky.fm!.
        /// </summary>
        public static string login_welcome {
            get {
                return ResourceManager.GetString("login_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buffer {0:P0}.
        /// </summary>
        public static string play_buffer_fmt {
            get {
                return ResourceManager.GetString("play_buffer_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play this channel.
        /// </summary>
        public static string play_button_playthis {
            get {
                return ResourceManager.GetString("play_button_playthis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume playback.
        /// </summary>
        public static string play_button_resume {
            get {
                return ResourceManager.GetString("play_button_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop playing.
        /// </summary>
        public static string play_button_stop {
            get {
                return ResourceManager.GetString("play_button_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Director: .
        /// </summary>
        public static string play_channelDirector {
            get {
                return ResourceManager.GetString("play_channelDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing error.
        /// </summary>
        public static string play_errormessage_title {
            get {
                return ResourceManager.GetString("play_errormessage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering.
        /// </summary>
        public static string play_status_buffering {
            get {
                return ResourceManager.GetString("play_status_buffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed due to an error: {0}.
        /// </summary>
        public static string play_status_failed_fmt {
            get {
                return ResourceManager.GetString("play_status_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traffic.
        /// </summary>
        public static string play_traffic {
            get {
                return ResourceManager.GetString("play_traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        public static string play_traffic_giga_fmt {
            get {
                return ResourceManager.GetString("play_traffic_giga_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string play_traffic_kilo_fmt {
            get {
                return ResourceManager.GetString("play_traffic_kilo_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        public static string play_traffic_mega_fmt {
            get {
                return ResourceManager.GetString("play_traffic_mega_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to rate this application in the marketplace, or write a review?.
        /// </summary>
        public static string rateapp_message_text {
            get {
                return ResourceManager.GetString("rateapp_message_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this application.
        /// </summary>
        public static string rateapp_message_title {
            get {
                return ResourceManager.GetString("rateapp_message_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.fm auto-generated problem report.
        /// </summary>
        public static string sendreport_message_mailSubject {
            get {
                return ResourceManager.GetString("sendreport_message_mailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application.
        ///Would you like to send an email to report it?.
        /// </summary>
        public static string sendreport_message_text {
            get {
                return ResourceManager.GetString("sendreport_message_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem report.
        /// </summary>
        public static string sendreport_message_title {
            get {
                return ResourceManager.GetString("sendreport_message_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium subscription is $50/year.
        ///Signup now?.
        /// </summary>
        public static string setting_signupMessage_text {
            get {
                return ResourceManager.GetString("setting_signupMessage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sky.fm premium.
        /// </summary>
        public static string setting_signupMessage_title {
            get {
                return ResourceManager.GetString("setting_signupMessage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} kbit/sec, {2}.
        /// </summary>
        public static string settings_chan_fmt {
            get {
                return ResourceManager.GetString("settings_chan_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free.
        /// </summary>
        public static string settings_chan_free {
            get {
                return ResourceManager.GetString("settings_chan_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premium.
        /// </summary>
        public static string settings_chan_premium {
            get {
                return ResourceManager.GetString("settings_chan_premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferences.
        /// </summary>
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the radio channels.
        ///{0}
        ///Press OK to retry..
        /// </summary>
        public static string splash_error_fmt {
            get {
                return ResourceManager.GetString("splash_error_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating channels….
        /// </summary>
        public static string splash_updating {
            get {
                return ResourceManager.GetString("splash_updating", resourceCulture);
            }
        }
    }
}
